# Generated by Django 6.0.3 on 2026-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_alter_fund_options_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'Payment History'},
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='fund_amount',
            field=models.IntegerField(),
        ),
    ]
