# Generated by Django 6.0.3 on 2026-03-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
