# Generated by Django 6.0.3 on 2026-03-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name_plural': 'Password Reset'},
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='uuid',
            new_name='reset_id',
        ),
    ]
